// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDITEM_H
#define DIALOGEVTCMDITEM_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdItem: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdItem::ids
    // end wxGlade

    DialogEvtCmdItem(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdItem::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdItem::attributes
    wxStaticBox* szOperand_staticbox;
    wxStaticBox* szObject_staticbox;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnObjectFixed;
    wxChoice* chObjectFixed;
    wxRadioButton* rbtnObjectVariable;
    wxTextCtrl* tcObjectVariable;
    wxButton* btnObjectVariable;
    wxRadioButton* rbtnOperandConstant;
    wxSpinCtrl* spinOperandConstant;
    wxRadioButton* rbtnOperandVariable;
    wxTextCtrl* tcOperandVariable;
    wxButton* btnOperandVariable;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDITEM_H
