// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDPLAYVIDEO_H
#define DIALOGEVTCMDPLAYVIDEO_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdPlayVideo: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdPlayVideo::ids
    // end wxGlade

    DialogEvtCmdPlayVideo(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdPlayVideo::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdPlayVideo::attributes
    wxStaticBox* szPosition_staticbox;
    wxStaticBox* szSize_staticbox;
    wxStaticBox* szFile_staticbox;
    wxTextCtrl* stVideo;
    wxButton* btnVideo;
    wxSpinCtrl* spinSizeX;
    wxStaticText* stSize;
    wxSpinCtrl* spinSizeY;
    wxRadioButton* rbtnSpecify;
    wxStaticText* szSpecifyX;
    wxSpinCtrl* spinSpecifyX;
    wxStaticText* stSpecifyY;
    wxSpinCtrl* spinSpecifyY;
    wxRadioButton* rbtnVariable;
    wxStaticText* stVariableX;
    wxTextCtrl* tcVariableX;
    wxButton* btnVariableX;
    wxStaticText* stVariableY;
    wxTextCtrl* tcVariableY;
    wxButton* btnVariableY;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDPLAYVIDEO_H
