// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDCHANGEESCAPEPLACE_H
#define DIALOGEVTCMDCHANGEESCAPEPLACE_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdChangeEscapePlace: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdChangeEscapePlace::ids
    // end wxGlade

    DialogEvtCmdChangeEscapePlace(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdChangeEscapePlace::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdChangeEscapePlace::attributes
    wxStaticBox* szSwitch_staticbox;
    wxStaticBox* szPosition_staticbox;
    wxTextCtrl* tcPosition;
    wxButton* btnPosition;
    wxCheckBox* chbSwitch;
    wxTextCtrl* tcSwitch;
    wxButton* btnSwitch;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDCHANGEESCAPEPLACE_H
