// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdAnimation.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdAnimation::DialogEvtCmdAnimation(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdAnimation::DialogEvtCmdAnimation
    szTarget_staticbox = new wxStaticBox(this, wxID_ANY, _("Target"));
    szOptions_staticbox = new wxStaticBox(this, wxID_ANY, _("Options"));
    SzAnimation2_staticbox = new wxStaticBox(this, wxID_ANY, _("Animation"));
    bmpAnimation = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN);
    const wxString chAnimation_choices[] = {
        _("<set by wxGlade>"),
    };
    chAnimation = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chAnimation_choices);
    const wxString chTarget_choices[] = {
        _("<set by wxGlade>"),
    };
    chTarget = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chTarget_choices);
    chbWait = new wxCheckBox(this, wxID_ANY, _("Wait until end"));
    chbWholeMapRange = new wxCheckBox(this, wxID_ANY, _("Whole map range"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdAnimation::set_properties()
{
    // begin wxGlade: DialogEvtCmdAnimation::set_properties
    SetTitle(_("Show animation"));
    bmpAnimation->SetMinSize(wxSize(320, 160));
    chAnimation->SetSelection(0);
    chTarget->SetSelection(0);
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdAnimation::do_layout()
{
    // begin wxGlade: DialogEvtCmdAnimation::do_layout
    wxBoxSizer* szAnimation = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szRight = new wxBoxSizer(wxVERTICAL);
    szOptions_staticbox->Lower();
    wxStaticBoxSizer* szOptions = new wxStaticBoxSizer(szOptions_staticbox, wxVERTICAL);
    szTarget_staticbox->Lower();
    wxStaticBoxSizer* szTarget = new wxStaticBoxSizer(szTarget_staticbox, wxHORIZONTAL);
    SzAnimation2_staticbox->Lower();
    wxStaticBoxSizer* SzAnimation2 = new wxStaticBoxSizer(SzAnimation2_staticbox, wxVERTICAL);
    SzAnimation2->Add(bmpAnimation, 0, wxALIGN_CENTER|wxBOTTOM, 1);
    SzAnimation2->Add(chAnimation, 0, wxBOTTOM|wxEXPAND, 1);
    szTop->Add(SzAnimation2, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szTarget->Add(chTarget, 1, 0, 0);
    szRight->Add(szTarget, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    szOptions->Add(chbWait, 0, wxBOTTOM|wxEXPAND, 1);
    szOptions->Add(chbWholeMapRange, 0, wxEXPAND|wxTOP, 1);
    szRight->Add(szOptions, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szTop->Add(szRight, 1, wxEXPAND, 0);
    szAnimation->Add(szTop, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szAnimation->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szAnimation);
    szAnimation->Fit(this);
    Layout();
    // end wxGlade
}

