// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDFADEMUSIC_H
#define DIALOGEVTCMDFADEMUSIC_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdFadeMusic: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdFadeMusic::ids
    // end wxGlade

    DialogEvtCmdFadeMusic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdFadeMusic::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdFadeMusic::attributes
    wxStaticBox* szTime_staticbox;
    wxSlider* slTime;
    wxStaticText* stTime0Seconds;
    wxStaticText* stTime5Seconds;
    wxStaticText* stTime10Seconds;
    wxStaticText* stTime15Seconds;
    wxStaticText* stTime20Seconds;
    wxButton* btnFade;
    wxButton* btnPlay;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDFADEMUSIC_H
