// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDTELEPORT_H
#define DIALOGEVTCMDTELEPORT_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
#include <wx/tglbtn.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdTeleport: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdTeleport::ids
    // end wxGlade

    DialogEvtCmdTeleport(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdTeleport::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdTeleport::attributes
    wxTreeCtrl* treeMaps;
    wxPanel* pnMap;
    wxStaticText* sTMap;
    wxToggleButton* btnScale11;
    wxToggleButton* btnScale12;
    wxToggleButton* btnScale14;
    wxButton* btnOK;
    wxButton* btnCancel;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDTELEPORT_H
