// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdCallEvent.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdCallEvent::DialogEvtCmdCallEvent(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdCallEvent::DialogEvtCmdCallEvent
    szEvent_staticbox = new wxStaticBox(this, wxID_ANY, _("Event to call"));
    rbtnCommonEvent = new wxRadioButton(this, wxID_ANY, _("Common event"));
    const wxString chCommonEvent_choices[] = {
        _("<set by wxGlade>"),
    };
    chCommonEvent = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chCommonEvent_choices);
    rbtnMapEvent = new wxRadioButton(this, wxID_ANY, _("Map event"));
    const wxString chMapEvent_choices[] = {
        _("<set by wxGlade>"),
    };
    chMapEvent = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chMapEvent_choices);
    spinMapEvent = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    stMapEvent = new wxStaticText(this, wxID_ANY, _("page"));
    rbtnMapEventVariable = new wxRadioButton(this, wxID_ANY, _("Map event by variable"));
    tcMapEventVariableEvent = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnMapEventVariableEvent = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    stMapEventVariableEvent = new wxStaticText(this, wxID_ANY, _("event to call"));
    tcMapEventVariablePage = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnMapEventVariablePage = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    stMapEventVariablePage = new wxStaticText(this, wxID_ANY, _("page"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdCallEvent::set_properties()
{
    // begin wxGlade: DialogEvtCmdCallEvent::set_properties
    SetTitle(_("Call event"));
    chCommonEvent->SetMinSize(wxSize(50, -1));
    chCommonEvent->SetSelection(0);
    chMapEvent->SetMinSize(wxSize(50, -1));
    chMapEvent->SetSelection(0);
    spinMapEvent->SetMinSize(wxSize(50, -1));
    tcMapEventVariableEvent->SetMinSize(wxSize(50, -1));
    tcMapEventVariablePage->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdCallEvent::do_layout()
{
    // begin wxGlade: DialogEvtCmdCallEvent::do_layout
    wxBoxSizer* szCallEvent = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szEvent_staticbox->Lower();
    wxStaticBoxSizer* szEvent = new wxStaticBoxSizer(szEvent_staticbox, wxVERTICAL);
    wxFlexGridSizer* gszMapEventVariable = new wxFlexGridSizer(2, 3, 2, 0);
    wxBoxSizer* szMapEvent = new wxBoxSizer(wxHORIZONTAL);
    szEvent->Add(rbtnCommonEvent, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxEXPAND, 1);
    szEvent->Add(chCommonEvent, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxEXPAND|wxTOP, 1);
    szEvent->Add(rbtnMapEvent, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxEXPAND|wxTOP, 1);
    szMapEvent->Add(chMapEvent, 1, wxALIGN_CENTER_VERTICAL|wxRIGHT, 1);
    szMapEvent->Add(spinMapEvent, 0, wxALIGN_CENTER_VERTICAL|wxLEFT|wxRIGHT, 1);
    szMapEvent->Add(stMapEvent, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 1);
    szEvent->Add(szMapEvent, 0, wxBOTTOM|wxEXPAND|wxTOP, 1);
    szEvent->Add(rbtnMapEventVariable, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxEXPAND|wxTOP, 1);
    gszMapEventVariable->Add(tcMapEventVariableEvent, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    gszMapEventVariable->Add(btnMapEventVariableEvent, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT, 1);
    gszMapEventVariable->Add(stMapEventVariableEvent, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 1);
    gszMapEventVariable->Add(tcMapEventVariablePage, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    gszMapEventVariable->Add(btnMapEventVariablePage, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT, 1);
    gszMapEventVariable->Add(stMapEventVariablePage, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 1);
    gszMapEventVariable->AddGrowableCol(0);
    szEvent->Add(gszMapEventVariable, 1, wxEXPAND|wxTOP, 1);
    szCallEvent->Add(szEvent, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szCallEvent->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szCallEvent);
    szCallEvent->Fit(this);
    Layout();
    // end wxGlade
}

