// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdChangeEscapePlace.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdChangeEscapePlace::DialogEvtCmdChangeEscapePlace(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdChangeEscapePlace::DialogEvtCmdChangeEscapePlace
    szSwitch_staticbox = new wxStaticBox(this, wxID_ANY, _("Enable switch after escape"));
    szPosition_staticbox = new wxStaticBox(this, wxID_ANY, _("Escape position"));
    tcPosition = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnPosition = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    chbSwitch = new wxCheckBox(this, wxID_ANY, _("Enable"));
    tcSwitch = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnSwitch = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdChangeEscapePlace::set_properties()
{
    // begin wxGlade: DialogEvtCmdChangeEscapePlace::set_properties
    SetTitle(_("Change escape place"));
    tcPosition->SetMinSize(wxSize(125, -1));
    tcSwitch->SetMinSize(wxSize(125, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdChangeEscapePlace::do_layout()
{
    // begin wxGlade: DialogEvtCmdChangeEscapePlace::do_layout
    wxBoxSizer* szEscapePlace = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szSwitch_staticbox->Lower();
    wxStaticBoxSizer* szSwitch = new wxStaticBoxSizer(szSwitch_staticbox, wxHORIZONTAL);
    szPosition_staticbox->Lower();
    wxStaticBoxSizer* szPosition = new wxStaticBoxSizer(szPosition_staticbox, wxHORIZONTAL);
    szPosition->Add(tcPosition, 1, wxALIGN_CENTER_VERTICAL, 0);
    szPosition->Add(btnPosition, 0, wxALIGN_CENTER_VERTICAL, 0);
    szEscapePlace->Add(szPosition, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    szSwitch->Add(chbSwitch, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT, 1);
    szSwitch->Add(tcSwitch, 1, wxALIGN_CENTER_VERTICAL|wxLEFT, 1);
    szSwitch->Add(btnSwitch, 0, wxALIGN_CENTER_VERTICAL, 0);
    szEscapePlace->Add(szSwitch, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szEscapePlace->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szEscapePlace);
    szEscapePlace->Fit(this);
    Layout();
    // end wxGlade
}

