// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDFLASHCHARACTER_H
#define DIALOGEVTCMDFLASHCHARACTER_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdFlashCharacter: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdFlashCharacter::ids
    // end wxGlade

    DialogEvtCmdFlashCharacter(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdFlashCharacter::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdFlashCharacter::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szTime_staticbox;
    wxStaticBox* szColor_staticbox;
    wxStaticBox* szSample_staticbox;
    wxStaticBox* szTarget_staticbox;
    wxChoice* chTarget;
    wxStaticBitmap* bmpSample;
    wxStaticText* stColorMin;
    wxStaticText* stColorMax;
    wxStaticText* stRed;
    wxSlider* slRed;
    wxSpinCtrl* spinRed;
    wxStaticText* stGreen;
    wxSlider* slGreen;
    wxSpinCtrl* spinGreen;
    wxStaticText* stBlue;
    wxSlider* slBlue;
    wxSpinCtrl* spinBlue;
    wxStaticText* stOpacity;
    wxSlider* slOpacity;
    wxSpinCtrl* spinOpacity;
    wxSpinCtrl* spinTime;
    wxStaticText* stTime;
    wxCheckBox* chbWait;
    wxButton* btnOK;
    wxButton* btnCancelBtnHel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDFLASHCHARACTER_H
