// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdMessage.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdMessage::DialogEvtCmdMessage(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdMessage::DialogEvtCmdMessage
    tcMessage = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_CHARWRAP|wxTE_MULTILINE|wxTE_WORDWRAP);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdMessage::set_properties()
{
    // begin wxGlade: DialogEvtCmdMessage::set_properties
    SetTitle(_("Show message"));
    tcMessage->SetMinSize(wxSize(523, 78));
    tcMessage->SetFont(wxFont(0, wxMODERN, wxNORMAL, wxNORMAL, 0, wxT("")));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdMessage::do_layout()
{
    // begin wxGlade: DialogEvtCmdMessage::do_layout
    wxBoxSizer* szMessage = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szMessage->Add(tcMessage, 1, wxALL|wxEXPAND, 1);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szMessage->Add(szBottom, 0, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szMessage);
    szMessage->Fit(this);
    Layout();
    // end wxGlade
}

