// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDMOVESCREEN_H
#define DIALOGEVTCMDMOVESCREEN_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdMoveScreen: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdMoveScreen::ids
    // end wxGlade

    DialogEvtCmdMoveScreen(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdMoveScreen::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdMoveScreen::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szSpeed_staticbox;
    wxStaticBox* szTiles_staticbox;
    wxStaticBox* szDirection_staticbox;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnUp;
    wxRadioButton* rbtnLeft;
    wxRadioButton* rbtnRight;
    wxRadioButton* rbtnDown;
    wxSpinCtrl* spinTiles;
    wxChoice* chSpeed;
    wxCheckBox* chbWait;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDMOVESCREEN_H
