// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdEventPosition.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdEventPosition::DialogEvtCmdEventPosition(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdEventPosition::DialogEvtCmdEventPosition
    szPositionVariable_staticbox = new wxStaticBox(this, wxID_ANY, _("Origin variable"));
    szPosition_staticbox = new wxStaticBox(this, wxID_ANY, _("Event position"));
    szEvent_staticbox = new wxStaticBox(this, wxID_ANY, _("Event"));
    const wxString chEvent_choices[] = {
        _("<set by wxGlade>"),
    };
    chEvent = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chEvent_choices);
    rbtnPositionEspecify = new wxRadioButton(this, wxID_ANY, _("Specify"));
    tcPositionEspecify = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnPositionEspecify = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    rbtnPositionVariable = new wxRadioButton(this, wxID_ANY, _("Variable"));
    stPositionVariableX = new wxStaticText(this, wxID_ANY, _("X ordinate:"));
    tcPositionVariableX = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnPositionVariableX = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    stPositionVariableY = new wxStaticText(this, wxID_ANY, _("Y ordinate:"));
    tcPositionVariableY = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnPositionVariableY = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdEventPosition::set_properties()
{
    // begin wxGlade: DialogEvtCmdEventPosition::set_properties
    SetTitle(_("Change event position"));
    chEvent->SetMinSize(wxSize(50, -1));
    chEvent->SetSelection(0);
    tcPositionEspecify->SetMinSize(wxSize(50, -1));
    tcPositionVariableX->SetMinSize(wxSize(50, -1));
    tcPositionVariableY->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdEventPosition::do_layout()
{
    // begin wxGlade: DialogEvtCmdEventPosition::do_layout
    wxBoxSizer* szEventPosition = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szPosition_staticbox->Lower();
    wxStaticBoxSizer* szPosition = new wxStaticBoxSizer(szPosition_staticbox, wxVERTICAL);
    szPositionVariable_staticbox->Lower();
    wxStaticBoxSizer* szPositionVariable = new wxStaticBoxSizer(szPositionVariable_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* gszPositionVariable = new wxFlexGridSizer(2, 2, 2, 2);
    wxBoxSizer* szPositionVariableY = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szPositionVariableX = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szPositionSpecify = new wxBoxSizer(wxHORIZONTAL);
    szEvent_staticbox->Lower();
    wxStaticBoxSizer* szEvent = new wxStaticBoxSizer(szEvent_staticbox, wxHORIZONTAL);
    szEvent->Add(chEvent, 1, wxALIGN_CENTER_VERTICAL, 0);
    szEventPosition->Add(szEvent, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    szPositionSpecify->Add(rbtnPositionEspecify, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxRIGHT, 1);
    szPositionSpecify->Add(tcPositionEspecify, 1, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxLEFT, 1);
    szPositionSpecify->Add(btnPositionEspecify, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM, 1);
    szPosition->Add(szPositionSpecify, 0, wxEXPAND, 0);
    szPosition->Add(rbtnPositionVariable, 0, wxEXPAND|wxTOP, 1);
    gszPositionVariable->Add(stPositionVariableX, 0, wxALIGN_CENTER_VERTICAL, 0);
    szPositionVariableX->Add(tcPositionVariableX, 1, wxALIGN_CENTER_VERTICAL, 0);
    szPositionVariableX->Add(btnPositionVariableX, 0, wxALIGN_CENTER_VERTICAL, 0);
    gszPositionVariable->Add(szPositionVariableX, 1, wxEXPAND, 0);
    gszPositionVariable->Add(stPositionVariableY, 0, wxALIGN_CENTER_VERTICAL, 0);
    szPositionVariableY->Add(tcPositionVariableY, 1, wxALIGN_CENTER_VERTICAL, 0);
    szPositionVariableY->Add(btnPositionVariableY, 0, wxALIGN_CENTER_VERTICAL, 0);
    gszPositionVariable->Add(szPositionVariableY, 1, wxEXPAND, 0);
    gszPositionVariable->AddGrowableCol(1);
    szPositionVariable->Add(gszPositionVariable, 1, wxEXPAND, 0);
    szPosition->Add(szPositionVariable, 0, wxEXPAND, 0);
    szEventPosition->Add(szPosition, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szEventPosition->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szEventPosition);
    szEventPosition->Fit(this);
    Layout();
    // end wxGlade
}

