// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDCOMMERCE_H
#define DIALOGEVTCMDCOMMERCE_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdCommerce: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdCommerce::ids
    // end wxGlade

    DialogEvtCmdCommerce(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdCommerce::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdCommerce::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szObjects_staticbox;
    wxStaticBox* szStyle_staticbox;
    wxRadioBox* rbType;
    wxChoice* chStyle;
    wxListBox* listSell;
    wxButton* btnAdd;
    wxButton* btnRemove;
    wxListBox* listObjects;
    wxCheckBox* chbDoNotResell;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDCOMMERCE_H
