// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdSystemSound.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdSystemSound::DialogEvtCmdSystemSound(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdSystemSound::DialogEvtCmdSystemSound
    szSound_staticbox = new wxStaticBox(this, wxID_ANY, _("Sound"));
    SzSystemSound2_staticbox = new wxStaticBox(this, wxID_ANY, _("Sound type"));
    const wxString chSystemSound_choices[] = {
        _("<set by wxGlade>"),
    };
    chSystemSound = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chSystemSound_choices);
    tcSound = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnSound = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdSystemSound::set_properties()
{
    // begin wxGlade: DialogEvtCmdSystemSound::set_properties
    SetTitle(_("Change system sound"));
    chSystemSound->SetMinSize(wxSize(50, -1));
    chSystemSound->SetSelection(0);
    tcSound->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdSystemSound::do_layout()
{
    // begin wxGlade: DialogEvtCmdSystemSound::do_layout
    wxBoxSizer* szSystemSound = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szSound_staticbox->Lower();
    wxStaticBoxSizer* szSound = new wxStaticBoxSizer(szSound_staticbox, wxHORIZONTAL);
    SzSystemSound2_staticbox->Lower();
    wxStaticBoxSizer* SzSystemSound2 = new wxStaticBoxSizer(SzSystemSound2_staticbox, wxHORIZONTAL);
    SzSystemSound2->Add(chSystemSound, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(SzSystemSound2, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szSound->Add(tcSound, 1, wxALIGN_CENTER_VERTICAL, 0);
    szSound->Add(btnSound, 0, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szSound, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szSystemSound->Add(szTop, 1, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szSystemSound->Add(szBottom, 0, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szSystemSound);
    szSystemSound->Fit(this);
    Layout();
    // end wxGlade
}

