// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDVARIABLE_H
#define DIALOGEVTCMDVARIABLE_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdVariable: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdVariable::ids
    // end wxGlade

    DialogEvtCmdVariable(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdVariable::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdVariable::attributes
    wxStaticBox* szOperand_staticbox;
    wxStaticBox* szSwitch_staticbox;
    wxRadioButton* rbtnSet;
    wxTextCtrl* tcSwitchSet;
    wxButton* btnSwitchSet;
    wxRadioButton* rbtnoSwitchRange;
    wxSpinCtrl* spinSwitchRange1;
    wxStaticText* tcSwitchRange;
    wxSpinCtrl* spinSwitchRange2;
    wxRadioButton* rbtnSwitchVariable;
    wxTextCtrl* tcSwitchVariable;
    wxButton* btnSwitchVariable;
    wxStaticText* stSwitchVariable;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnOperandConstant;
    wxSpinCtrl* spinOperandConstant;
    wxRadioButton* rbtnOperandVariableA;
    wxTextCtrl* tcOperandVariableA;
    wxButton* btnOperandVariableA;
    wxRadioButton* rbtnOperandVariableB;
    wxTextCtrl* tcOperandVariableB;
    wxButton* btnOperandVariableB;
    wxStaticText* stOperandVarVaiableB;
    wxRadioButton* rbtnOperandRandom;
    wxSpinCtrl* spinOperandRandom1;
    wxSpinCtrl* spinOperandRandom2;
    wxRadioButton* rbtnOperandObject;
    wxChoice* chOperandObject;
    wxChoice* chOperandObject2;
    wxRadioButton* rbtnOperandActor;
    wxChoice* chOperandActor;
    wxChoice* chOperandActor2;
    wxRadioButton* rbtnOperandSprite;
    wxChoice* chOperandSprite;
    wxChoice* chOperandSprite2;
    wxRadioButton* rbtnOperandPut;
    wxChoice* chOperandPut;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDVARIABLE_H
