// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDPLAYSOUND_H
#define DIALOGEVTCMDPLAYSOUND_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdPlaySound: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdPlaySound::ids
    // end wxGlade

    DialogEvtCmdPlaySound(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdPlaySound::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdPlaySound::attributes
    wxStaticBox* szBalance_staticbox;
    wxStaticBox* szTempo_staticbox;
    wxStaticBox* szVolume_staticbox;
    wxStaticBox* szFadeIn_staticbox;
    wxListBox* listSound;
    wxSlider* slFadeIn;
    wxStaticText* stFadeInNone;
    wxStaticText* stFadeIn5Seconds;
    wxStaticText* stFadeIn10Seconds;
    wxSlider* slVolume;
    wxStaticText* stVolume0Percent;
    wxStaticText* stVolume50Percent;
    wxStaticText* stVolume100Percent;
    wxSlider* slTempo;
    wxStaticText* stTempo50Percent;
    wxStaticText* stTempo100Percent;
    wxStaticText* stTempo150Percent;
    wxSlider* slBalance;
    wxStaticText* stBalanceLeft;
    wxStaticText* stBalanceCenter;
    wxStaticText* stBalanceRight;
    wxButton* btnPlay;
    wxButton* btnStop;
    wxStaticLine* linePlayMusic;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDPLAYSOUND_H
