// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdCommerce.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdCommerce::DialogEvtCmdCommerce(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdCommerce::DialogEvtCmdCommerce
    szObjects_staticbox = new wxStaticBox(this, wxID_ANY, _("Objects to sell"));
    szOptions_staticbox = new wxStaticBox(this, wxID_ANY, _("Options"));
    szStyle_staticbox = new wxStaticBox(this, wxID_ANY, _("Commerce style"));
    const wxString rbType_choices[] = {
        _("Normal"),
        _("Doesn't sell"),
        _("Doesn't buy"),
    };
    rbType = new wxRadioBox(this, wxID_ANY, _("Commerce type"), wxDefaultPosition, wxDefaultSize, 3, rbType_choices, 1, wxRA_SPECIFY_ROWS);
    const wxString chStyle_choices[] = {
        _("<set by wxGlade>"),
    };
    chStyle = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chStyle_choices);
    const wxString listSell_choices[] = {
        _("<set by wxGlade>"),
    };
    listSell = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, listSell_choices, wxLB_SINGLE);
    btnAdd = new wxButton(this, wxID_ANY, _("< Add"), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnRemove = new wxButton(this, wxID_ANY, _("Remove >"), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    const wxString listObjects_choices[] = {
        _("<set by wxGlade>"),
    };
    listObjects = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, listObjects_choices, wxLB_SINGLE);
    chbDoNotResell = new wxCheckBox(this, wxID_ANY, _("Merchant doesn't sell goods already sold"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdCommerce::set_properties()
{
    // begin wxGlade: DialogEvtCmdCommerce::set_properties
    SetTitle(_("Visit commerce"));
    rbType->SetSelection(0);
    chStyle->SetMinSize(wxSize(50, -1));
    chStyle->SetSelection(0);
    listSell->SetMinSize(wxSize(50, -1));
    listSell->SetSelection(0);
    listObjects->SetMinSize(wxSize(50, -1));
    listObjects->SetSelection(0);
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdCommerce::do_layout()
{
    // begin wxGlade: DialogEvtCmdCommerce::do_layout
    wxBoxSizer* szCommerce = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szOptions_staticbox->Lower();
    wxStaticBoxSizer* szOptions = new wxStaticBoxSizer(szOptions_staticbox, wxHORIZONTAL);
    szObjects_staticbox->Lower();
    wxStaticBoxSizer* szObjects = new wxStaticBoxSizer(szObjects_staticbox, wxHORIZONTAL);
    wxBoxSizer* szAddRemove = new wxBoxSizer(wxVERTICAL);
    szStyle_staticbox->Lower();
    wxStaticBoxSizer* szStyle = new wxStaticBoxSizer(szStyle_staticbox, wxHORIZONTAL);
    szCommerce->Add(rbType, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    szStyle->Add(chStyle, 1, 0, 0);
    szCommerce->Add(szStyle, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    szObjects->Add(listSell, 1, wxEXPAND|wxRIGHT, 1);
    szAddRemove->Add(0, 0, 1, wxEXPAND, 0);
    szAddRemove->Add(btnAdd, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szAddRemove->Add(btnRemove, 0, wxEXPAND|wxLEFT|wxRIGHT|wxTOP, 1);
    szAddRemove->Add(0, 0, 1, wxEXPAND, 0);
    szObjects->Add(szAddRemove, 0, wxEXPAND, 0);
    szObjects->Add(listObjects, 1, wxEXPAND|wxLEFT, 1);
    szCommerce->Add(szObjects, 1, wxEXPAND|wxLEFT|wxRIGHT, 1);
    szOptions->Add(chbDoNotResell, 1, 0, 0);
    szCommerce->Add(szOptions, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szCommerce->Add(szBottom, 0, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szCommerce);
    szCommerce->Fit(this);
    Layout();
    // end wxGlade
}

