// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdFadeMusic.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdFadeMusic::DialogEvtCmdFadeMusic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdFadeMusic::DialogEvtCmdFadeMusic
    szTime_staticbox = new wxStaticBox(this, wxID_ANY, _("Fade time"));
    slTime = new wxSlider(this, wxID_ANY, 5, 0, 20, wxDefaultPosition, wxDefaultSize, wxSL_AUTOTICKS|wxSL_HORIZONTAL);
    stTime0Seconds = new wxStaticText(this, wxID_ANY, _("0 sec"));
    stTime5Seconds = new wxStaticText(this, wxID_ANY, _("5 sec"));
    stTime10Seconds = new wxStaticText(this, wxID_ANY, _("10 sec"));
    stTime15Seconds = new wxStaticText(this, wxID_ANY, _("15 sec"));
    stTime20Seconds = new wxStaticText(this, wxID_ANY, _("20 sec"));
    btnFade = new wxButton(this, wxID_ANY, _("Fade"));
    btnPlay = new wxButton(this, wxID_ANY, _("Play"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdFadeMusic::set_properties()
{
    // begin wxGlade: DialogEvtCmdFadeMusic::set_properties
    SetTitle(_("Fade music"));
    slTime->SetMinSize(wxSize(200, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdFadeMusic::do_layout()
{
    // begin wxGlade: DialogEvtCmdFadeMusic::do_layout
    wxBoxSizer* szFadeMusic = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szTime_staticbox->Lower();
    wxStaticBoxSizer* szTime = new wxStaticBoxSizer(szTime_staticbox, wxHORIZONTAL);
    wxBoxSizer* szTimeLeft = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* slTimeBottom = new wxBoxSizer(wxHORIZONTAL);
    szTimeLeft->Add(slTime, 0, wxEXPAND, 0);
    slTimeBottom->Add(stTime0Seconds, 0, wxRIGHT, 1);
    slTimeBottom->Add(0, 0, 1, wxEXPAND, 0);
    slTimeBottom->Add(stTime5Seconds, 0, wxLEFT|wxRIGHT, 1);
    slTimeBottom->Add(0, 0, 1, wxEXPAND, 0);
    slTimeBottom->Add(stTime10Seconds, 0, wxLEFT|wxRIGHT, 1);
    slTimeBottom->Add(0, 0, 1, wxEXPAND, 0);
    slTimeBottom->Add(stTime15Seconds, 0, wxLEFT|wxRIGHT, 1);
    slTimeBottom->Add(0, 0, 1, wxEXPAND, 0);
    slTimeBottom->Add(stTime20Seconds, 0, wxLEFT, 1);
    szTimeLeft->Add(slTimeBottom, 0, wxEXPAND, 0);
    szTime->Add(szTimeLeft, 1, wxEXPAND, 0);
    szTime->Add(btnFade, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT, 1);
    szTime->Add(btnPlay, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 1);
    szFadeMusic->Add(szTime, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szFadeMusic->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szFadeMusic);
    szFadeMusic->Fit(this);
    Layout();
    // end wxGlade
}

