// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdActorFaceGraphic.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdActorFaceGraphic::DialogEvtCmdActorFaceGraphic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdActorFaceGraphic::DialogEvtCmdActorFaceGraphic
    szFaceGraphic_staticbox = new wxStaticBox(this, wxID_ANY, _("Face graphic"));
    szActor_staticbox = new wxStaticBox(this, wxID_ANY, _("Actor"));
    const wxString chActor_choices[] = {
        _("<set by wxGlade>"),
    };
    chActor = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chActor_choices);
    bmpFaceGraphic = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN);
    btnFaceGraphic = new wxButton(this, wxID_ANY, _("Select..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdActorFaceGraphic::set_properties()
{
    // begin wxGlade: DialogEvtCmdActorFaceGraphic::set_properties
    SetTitle(_("Change actor face graphic"));
    chActor->SetMinSize(wxSize(100, -1));
    chActor->SetSelection(0);
    bmpFaceGraphic->SetMinSize(wxSize(96, 96));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdActorFaceGraphic::do_layout()
{
    // begin wxGlade: DialogEvtCmdActorFaceGraphic::do_layout
    wxBoxSizer* szActorFaceGraphic = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szFaceGraphic_staticbox->Lower();
    wxStaticBoxSizer* szFaceGraphic = new wxStaticBoxSizer(szFaceGraphic_staticbox, wxHORIZONTAL);
    szActor_staticbox->Lower();
    wxStaticBoxSizer* szActor = new wxStaticBoxSizer(szActor_staticbox, wxHORIZONTAL);
    szActor->Add(chActor, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szActor, 2, wxBOTTOM|wxLEFT|wxRIGHT, 1);
    szFaceGraphic->Add(bmpFaceGraphic, 0, wxRIGHT, 1);
    szFaceGraphic->Add(btnFaceGraphic, 1, wxLEFT, 1);
    szTop->Add(szFaceGraphic, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szActorFaceGraphic->Add(szTop, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szActorFaceGraphic->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szActorFaceGraphic);
    szActorFaceGraphic->Fit(this);
    Layout();
    // end wxGlade
}

