// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDSHAKE_H
#define DIALOGEVTCMDSHAKE_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdShake: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdShake::ids
    // end wxGlade

    DialogEvtCmdShake(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdShake::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdShake::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szTime_staticbox;
    wxStaticBox* szSpeed_staticbox;
    wxStaticBox* szStrength_staticbox;
    wxSlider* slStrength;
    wxStaticText* stStrengthLower;
    wxStaticText* szStrengthNormal;
    wxStaticText* stStrengthHigher;
    wxSlider* slSpeed;
    wxStaticText* stSpeedSlower;
    wxStaticText* stSpeedNormal;
    wxStaticText* stSpeedFaster;
    wxSpinCtrl* spinTime;
    wxStaticText* stTime;
    wxCheckBox* chbWait;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDSHAKE_H
