// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDCONDITIONS_H
#define DIALOGEVTCMDCONDITIONS_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/notebook.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdConditions: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdConditions::ids
    // end wxGlade

    DialogEvtCmdConditions(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdConditions::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdConditions::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szConditionsTop_staticbox;
    wxRadioButton* rbtnSwitch;
    wxTextCtrl* tcSwitch;
    wxButton* btnSwitch;
    wxStaticText* stSwitch;
    wxChoice* chSwitch;
    wxRadioButton* rbtnVariable;
    wxTextCtrl* tcVariable;
    wxButton* btnVariable;
    wxStaticText* stVariable;
    wxRadioButton* rbtnVariableFixed;
    wxSpinCtrl* spinVariableFiexd;
    wxRadioButton* rbtnVariableVariable;
    wxTextCtrl* tcVariableVariable;
    wxButton* btnVariableVariable;
    wxChoice* chVariable;
    wxRadioButton* rbtnTimer;
    wxSpinCtrl* spinTimerMinutes;
    wxStaticText* stTimerMinutes;
    wxSpinCtrl* spinTimerSeconds;
    wxStaticText* stTimerSeconds;
    wxChoice* chTimer;
    wxRadioButton* rbtnMoney;
    wxSpinCtrl* spinMoney;
    wxChoice* chMoney;
    wxPanel* pnConditions1;
    wxRadioButton* rbtnItem;
    wxChoice* chItem;
    wxChoice* chItem2;
    wxRadioButton* rbtnoActor;
    wxChoice* chActor;
    wxTextCtrl* tcActor2;
    wxButton* btnActor;
    wxRadioButton* rbtnGroup;
    wxChoice* chGroup;
    wxStaticText* stGroup;
    wxChoice* chGroup2;
    wxStaticText* stGroup2;
    wxRadioButton* rbtnVehicle;
    wxChoice* chVehicle;
    wxStaticText* stVehicle;
    wxRadioButton* rbtnKey;
    wxRadioButton* rbtnMusic;
    wxPanel* nbConditions2;
    wxNotebook* nbConditions;
    wxCheckBox* chbElse;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDCONDITIONS_H
