// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdFlashScreen.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdFlashScreen::DialogEvtCmdFlashScreen(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdFlashScreen::DialogEvtCmdFlashScreen
    szColor_staticbox = new wxStaticBox(this, wxID_ANY, _("Flash color"));
    szTime_staticbox = new wxStaticBox(this, wxID_ANY, _("Time"));
    szOptions_staticbox = new wxStaticBox(this, wxID_ANY, _("Options"));
    szSample_staticbox = new wxStaticBox(this, wxID_ANY, _("Sample"));
    bmpSample = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN);
    stMin = new wxStaticText(this, wxID_ANY, _("0"));
    stMax = new wxStaticText(this, wxID_ANY, _("31"));
    stRed = new wxStaticText(this, wxID_ANY, _("Red"));
    slRed = new wxSlider(this, wxID_ANY, 31, 0, 31);
    spinRed = new wxSpinCtrl(this, wxID_ANY, wxT("31"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 31);
    stGreen = new wxStaticText(this, wxID_ANY, _("Green"));
    slGreen = new wxSlider(this, wxID_ANY, 31, 0, 31);
    spinGreen = new wxSpinCtrl(this, wxID_ANY, wxT("31"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 31);
    stBlue = new wxStaticText(this, wxID_ANY, _("Blue"));
    slBlue = new wxSlider(this, wxID_ANY, 31, 0, 31);
    spinBlue = new wxSpinCtrl(this, wxID_ANY, wxT("31"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 31);
    stOpacity = new wxStaticText(this, wxID_ANY, _("Opacity"));
    slOpacity = new wxSlider(this, wxID_ANY, 31, 0, 31);
    spinOpacity = new wxSpinCtrl(this, wxID_ANY, wxT("31"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 31);
    spinTime = new wxSpinCtrl(this, wxID_ANY, wxT("10"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    stTime = new wxStaticText(this, wxID_ANY, _("x0.1 sec."));
    chbWait = new wxCheckBox(this, wxID_ANY, _("Wait to end"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdFlashScreen::set_properties()
{
    // begin wxGlade: DialogEvtCmdFlashScreen::set_properties
    SetTitle(_("Flash screen"));
    bmpSample->SetMinSize(wxSize(48, 64));
    spinRed->SetMinSize(wxSize(50, -1));
    spinGreen->SetMinSize(wxSize(50, -1));
    spinBlue->SetMinSize(wxSize(50, -1));
    spinOpacity->SetMinSize(wxSize(50, -1));
    spinTime->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdFlashScreen::do_layout()
{
    // begin wxGlade: DialogEvtCmdFlashScreen::do_layout
    wxBoxSizer* szFlashScreen = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szMiddle = new wxBoxSizer(wxHORIZONTAL);
    szOptions_staticbox->Lower();
    wxStaticBoxSizer* szOptions = new wxStaticBoxSizer(szOptions_staticbox, wxHORIZONTAL);
    szTime_staticbox->Lower();
    wxStaticBoxSizer* szTime = new wxStaticBoxSizer(szTime_staticbox, wxHORIZONTAL);
    szColor_staticbox->Lower();
    wxStaticBoxSizer* szColor = new wxStaticBoxSizer(szColor_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* szColorRight = new wxFlexGridSizer(5, 3, 2, 2);
    wxBoxSizer* SzColorRightTop = new wxBoxSizer(wxHORIZONTAL);
    szSample_staticbox->Lower();
    wxStaticBoxSizer* szSample = new wxStaticBoxSizer(szSample_staticbox, wxHORIZONTAL);
    szSample->Add(bmpSample, 0, 0, 0);
    szColor->Add(szSample, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT, 2);
    szColorRight->Add(0, 0, 0, wxEXPAND, 0);
    SzColorRightTop->Add(stMin, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT, 1);
    SzColorRightTop->Add(0, 0, 1, wxEXPAND, 0);
    SzColorRightTop->Add(stMax, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 1);
    szColorRight->Add(SzColorRightTop, 1, wxEXPAND, 0);
    szColorRight->Add(0, 0, 0, wxEXPAND, 0);
    szColorRight->Add(stRed, 0, wxALIGN_CENTER, 0);
    szColorRight->Add(slRed, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    szColorRight->Add(spinRed, 0, wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(stGreen, 0, wxALIGN_CENTER, 0);
    szColorRight->Add(slGreen, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    szColorRight->Add(spinGreen, 0, wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(stBlue, 0, wxALIGN_CENTER, 0);
    szColorRight->Add(slBlue, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    szColorRight->Add(spinBlue, 0, wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->Add(stOpacity, 0, wxALIGN_CENTER, 0);
    szColorRight->Add(slOpacity, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    szColorRight->Add(spinOpacity, 0, wxALIGN_CENTER_VERTICAL, 0);
    szColorRight->AddGrowableCol(1);
    szColor->Add(szColorRight, 1, 0, 0);
    szFlashScreen->Add(szColor, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    szTime->Add(spinTime, 1, wxALIGN_CENTER_VERTICAL|wxRIGHT, 1);
    szTime->Add(stTime, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 1);
    szMiddle->Add(szTime, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szOptions->Add(chbWait, 1, wxALIGN_CENTER_VERTICAL, 0);
    szMiddle->Add(szOptions, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szFlashScreen->Add(szMiddle, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szFlashScreen->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szFlashScreen);
    szFlashScreen->Fit(this);
    Layout();
    // end wxGlade
}

