// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdTransition.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdTransition::DialogEvtCmdTransition(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdTransition::DialogEvtCmdTransition
    szOut_staticbox = new wxStaticBox(this, wxID_ANY, _("Out"));
    szIn_staticbox = new wxStaticBox(this, wxID_ANY, _("In"));
    const wxString chIn_choices[] = {
        _("<set by wxGlade>"),
    };
    chIn = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chIn_choices);
    const wxString chOut_choices[] = {
        _("<set by wxGlade>"),
    };
    chOut = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chOut_choices);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdTransition::set_properties()
{
    // begin wxGlade: DialogEvtCmdTransition::set_properties
    SetTitle(_("Change window transition"));
    chIn->SetMinSize(wxSize(50, -1));
    chIn->SetSelection(0);
    chOut->SetMinSize(wxSize(50, -1));
    chOut->SetSelection(0);
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdTransition::do_layout()
{
    // begin wxGlade: DialogEvtCmdTransition::do_layout
    wxBoxSizer* szTransition = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szOut_staticbox->Lower();
    wxStaticBoxSizer* szOut = new wxStaticBoxSizer(szOut_staticbox, wxHORIZONTAL);
    szIn_staticbox->Lower();
    wxStaticBoxSizer* szIn = new wxStaticBoxSizer(szIn_staticbox, wxHORIZONTAL);
    szIn->Add(chIn, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szIn, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szOut->Add(chOut, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szOut, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szTransition->Add(szTop, 1, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szTransition->Add(szBottom, 0, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szTransition);
    szTransition->Fit(this);
    Layout();
    // end wxGlade
}

