// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdNumberInput.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdNumberInput::DialogEvtCmdNumberInput(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdNumberInput::DialogEvtCmdNumberInput
    szVariable_staticbox = new wxStaticBox(this, wxID_ANY, _("Store value in variable"));
    szFigures_staticbox = new wxStaticBox(this, wxID_ANY, _("Number of figures"));
    spinFigures = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    tcVariable = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnVariable = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdNumberInput::set_properties()
{
    // begin wxGlade: DialogEvtCmdNumberInput::set_properties
    SetTitle(_("Show number input"));
    spinFigures->SetMinSize(wxSize(95, -1));
    tcVariable->SetMinSize(wxSize(125, -1));
    btnVariable->SetMinSize(wxSize(-1, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdNumberInput::do_layout()
{
    // begin wxGlade: DialogEvtCmdNumberInput::do_layout
    wxBoxSizer* szNumberInput = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szVariable_staticbox->Lower();
    wxStaticBoxSizer* szVariable = new wxStaticBoxSizer(szVariable_staticbox, wxHORIZONTAL);
    szFigures_staticbox->Lower();
    wxStaticBoxSizer* szFigures = new wxStaticBoxSizer(szFigures_staticbox, wxHORIZONTAL);
    szFigures->Add(spinFigures, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szFigures, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szVariable->Add(tcVariable, 1, wxALIGN_CENTER_VERTICAL, 0);
    szVariable->Add(btnVariable, 0, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szVariable, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szNumberInput->Add(szTop, 1, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szNumberInput->Add(szBottom, 0, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szNumberInput);
    szNumberInput->Fit(this);
    Layout();
    // end wxGlade
}

