// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdTeleport.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdTeleport::DialogEvtCmdTeleport(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdTeleport::DialogEvtCmdTeleport
    treeMaps = new wxTreeCtrl(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxTR_DEFAULT_STYLE|wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT|wxTR_NO_LINES);
    pnMap = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSUNKEN_BORDER|wxTAB_TRAVERSAL);
    sTMap = new wxStaticText(this, wxID_ANY, _("XXXX:MAPXXXX (XXX,YYY)"));
    btnScale11 = new wxToggleButton(this, wxID_ANY, _("1:1"));
    btnScale12 = new wxToggleButton(this, wxID_ANY, _("1:2"));
    btnScale14 = new wxToggleButton(this, wxID_ANY, _("1:4"));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdTeleport::set_properties()
{
    // begin wxGlade: DialogEvtCmdTeleport::set_properties
    SetTitle(_("Teleport"));
    treeMaps->SetMinSize(wxSize(150, -1));
    pnMap->SetMinSize(wxSize(320, 240));
    btnScale11->SetMinSize(wxSize(35, -1));
    btnScale12->SetMinSize(wxSize(35, -1));
    btnScale14->SetMinSize(wxSize(35, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdTeleport::do_layout()
{
    // begin wxGlade: DialogEvtCmdTeleport::do_layout
    wxBoxSizer* szTeleport = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szTop->Add(treeMaps, 0, wxALL|wxEXPAND, 1);
    szTop->Add(pnMap, 1, wxALL|wxEXPAND, 1);
    szTeleport->Add(szTop, 1, wxEXPAND, 0);
    szBottom->Add(sTMap, 10, wxALIGN_CENTER_VERTICAL|wxALL, 1);
    szBottom->Add(btnScale11, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxLEFT|wxTOP, 1);
    szBottom->Add(btnScale12, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxTOP, 1);
    szBottom->Add(btnScale14, 0, wxALIGN_CENTER_VERTICAL|wxBOTTOM|wxRIGHT|wxTOP, 1);
    szBottom->Add(0, 0, 1, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALIGN_CENTER_VERTICAL|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_CENTER_VERTICAL|wxALL, 1);
    szTeleport->Add(szBottom, 0, wxBOTTOM|wxEXPAND|wxRIGHT, 3);
    SetSizer(szTeleport);
    szTeleport->Fit(this);
    Layout();
    // end wxGlade
}

