// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDEVENTPOSITION_H
#define DIALOGEVTCMDEVENTPOSITION_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdEventPosition: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdEventPosition::ids
    // end wxGlade

    DialogEvtCmdEventPosition(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdEventPosition::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdEventPosition::attributes
    wxStaticBox* szPosition_staticbox;
    wxStaticBox* szPositionVariable_staticbox;
    wxStaticBox* szEvent_staticbox;
    wxChoice* chEvent;
    wxRadioButton* rbtnPositionEspecify;
    wxTextCtrl* tcPositionEspecify;
    wxButton* btnPositionEspecify;
    wxRadioButton* rbtnPositionVariable;
    wxStaticText* stPositionVariableX;
    wxTextCtrl* tcPositionVariableX;
    wxButton* btnPositionVariableX;
    wxStaticText* stPositionVariableY;
    wxTextCtrl* tcPositionVariableY;
    wxButton* btnPositionVariableY;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDEVENTPOSITION_H
