// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdActorGraphic.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdActorGraphic::DialogEvtCmdActorGraphic(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdActorGraphic::DialogEvtCmdActorGraphic
    szGraphic_staticbox = new wxStaticBox(this, wxID_ANY, _("Graphic"));
    szActor_staticbox = new wxStaticBox(this, wxID_ANY, _("Actor"));
    const wxString chActor_choices[] = {
        _("<set by wxGlade>"),
    };
    chActor = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chActor_choices);
    bmpGraphic = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN);
    chbTranslucent = new wxCheckBox(this, wxID_ANY, _("Translucent"));
    btnGraphic = new wxButton(this, wxID_ANY, _("Select..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdActorGraphic::set_properties()
{
    // begin wxGlade: DialogEvtCmdActorGraphic::set_properties
    SetTitle(_("Change actor graphic"));
    chActor->SetMinSize(wxSize(100, -1));
    chActor->SetSelection(0);
    bmpGraphic->SetMinSize(wxSize(48, 64));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdActorGraphic::do_layout()
{
    // begin wxGlade: DialogEvtCmdActorGraphic::do_layout
    wxBoxSizer* szActorGraphic = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szTop = new wxBoxSizer(wxHORIZONTAL);
    szGraphic_staticbox->Lower();
    wxStaticBoxSizer* szGraphic = new wxStaticBoxSizer(szGraphic_staticbox, wxHORIZONTAL);
    wxBoxSizer* szOptions = new wxBoxSizer(wxVERTICAL);
    szActor_staticbox->Lower();
    wxStaticBoxSizer* szActor = new wxStaticBoxSizer(szActor_staticbox, wxHORIZONTAL);
    szActor->Add(chActor, 1, wxALIGN_CENTER_VERTICAL, 0);
    szTop->Add(szActor, 1, wxBOTTOM|wxLEFT|wxRIGHT, 1);
    szGraphic->Add(bmpGraphic, 0, wxRIGHT, 1);
    szOptions->Add(chbTranslucent, 0, wxBOTTOM|wxLEFT, 1);
    szOptions->Add(btnGraphic, 0, wxEXPAND|wxLEFT|wxTOP, 1);
    szGraphic->Add(szOptions, 0, wxEXPAND, 0);
    szTop->Add(szGraphic, 0, wxBOTTOM|wxLEFT|wxRIGHT, 1);
    szActorGraphic->Add(szTop, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szActorGraphic->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szActorGraphic);
    szActorGraphic->Fit(this);
    Layout();
    // end wxGlade
}

