// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef DIALOGEVTCMDTIMER_H
#define DIALOGEVTCMDTIMER_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "appEditor"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class DialogEvtCmdTimer: public wxDialog {
public:
    // begin wxGlade: DialogEvtCmdTimer::ids
    // end wxGlade

    DialogEvtCmdTimer(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DialogEvtCmdTimer::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DialogEvtCmdTimer::attributes
    wxStaticBox* szOptions_staticbox;
    wxStaticBox* szOperation_staticbox;
    wxRadioBox* rbOperation;
    wxRadioButton* rbtnSet;
    wxSpinCtrl* spinMinutes;
    wxStaticText* stMinutes;
    wxSpinCtrl* spinSeconds;
    wxStaticText* stSeconds;
    wxRadioButton* rbtnVariable;
    wxTextCtrl* tcVariable;
    wxButton* btnVariable;
    wxCheckBox* chbShowScreen;
    wxCheckBox* chbShowBattle;
    wxButton* btnOK;
    wxButton* btnCancel;
    wxButton* btnHelp;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGEVTCMDTIMER_H
