// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdMoney.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdMoney::DialogEvtCmdMoney(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdMoney::DialogEvtCmdMoney
    SzOperandRight_staticbox = new wxStaticBox(this, wxID_ANY, _("Operand"));
    const wxString rbOperation_choices[] = {
        _("Increase"),
        _("Decrease"),
    };
    rbOperation = new wxRadioBox(this, wxID_ANY, _("Operation"), wxDefaultPosition, wxDefaultSize, 2, rbOperation_choices, 1, wxRA_SPECIFY_ROWS);
    RadioConstant = new wxRadioButton(this, wxID_ANY, _("Constant"));
    SpinConstant = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    RadioVar = new wxRadioButton(this, wxID_ANY, _("Variable"));
    TextVar = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    BtnVar = new wxButton(this, wxID_ANY, _("..."));
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdMoney::set_properties()
{
    // begin wxGlade: DialogEvtCmdMoney::set_properties
    SetTitle(_("Change money amount"));
    rbOperation->SetSelection(0);
    SpinConstant->SetMinSize(wxSize(60, -1));
    TextVar->SetMinSize(wxSize(75, -1));
    BtnVar->SetMinSize(wxSize(25, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdMoney::do_layout()
{
    // begin wxGlade: DialogEvtCmdMoney::do_layout
    wxBoxSizer* szMoney = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    SzOperandRight_staticbox->Lower();
    wxStaticBoxSizer* SzOperandRight = new wxStaticBoxSizer(SzOperandRight_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* SzOperandUp = new wxFlexGridSizer(2, 2, 2, 2);
    wxBoxSizer* SzVar = new wxBoxSizer(wxHORIZONTAL);
    szMoney->Add(rbOperation, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    SzOperandUp->Add(RadioConstant, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    SzOperandUp->Add(SpinConstant, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    SzOperandUp->Add(RadioVar, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    SzVar->Add(TextVar, 1, wxALIGN_CENTER_VERTICAL, 0);
    SzVar->Add(BtnVar, 0, wxALIGN_CENTER_VERTICAL, 0);
    SzOperandUp->Add(SzVar, 1, wxEXPAND, 0);
    SzOperandUp->AddGrowableCol(1);
    SzOperandRight->Add(SzOperandUp, 1, wxEXPAND, 0);
    szMoney->Add(SzOperandRight, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szMoney->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szMoney);
    szMoney->Fit(this);
    Layout();
    // end wxGlade
}

