// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdTile.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdTile::DialogEvtCmdTile(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdTile::DialogEvtCmdTile
    szReplacer_staticbox = new wxStaticBox(this, wxID_ANY, _("Replace with"));
    szOriginal_staticbox = new wxStaticBox(this, wxID_ANY, _("Tile to replace"));
    const wxString rbOptions_choices[] = {
        _("Lower"),
        _("Upper"),
    };
    rbOptions = new wxRadioBox(this, wxID_ANY, _("Tile type"), wxDefaultPosition, wxDefaultSize, 2, rbOptions_choices, 1, wxRA_SPECIFY_ROWS);
    bmpOriginal = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN);
    btnOriginal = new wxButton(this, wxID_ANY, _("Select..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    bmpReplacer = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN);
    btnReplacer = new wxButton(this, wxID_ANY, _("Select..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdTile::set_properties()
{
    // begin wxGlade: DialogEvtCmdTile::set_properties
    SetTitle(_("Change tile"));
    rbOptions->SetSelection(0);
    bmpOriginal->SetMinSize(wxSize(32, 32));
    bmpReplacer->SetMinSize(wxSize(32, 32));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdTile::do_layout()
{
    // begin wxGlade: DialogEvtCmdTile::do_layout
    wxBoxSizer* szTile = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* szMiddle = new wxBoxSizer(wxHORIZONTAL);
    szReplacer_staticbox->Lower();
    wxStaticBoxSizer* szReplacer = new wxStaticBoxSizer(szReplacer_staticbox, wxHORIZONTAL);
    szOriginal_staticbox->Lower();
    wxStaticBoxSizer* szOriginal = new wxStaticBoxSizer(szOriginal_staticbox, wxHORIZONTAL);
    szTile->Add(rbOptions, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    szOriginal->Add(bmpOriginal, 0, wxRIGHT, 1);
    szOriginal->Add(btnOriginal, 0, wxLEFT, 1);
    szMiddle->Add(szOriginal, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szReplacer->Add(bmpReplacer, 0, wxRIGHT, 1);
    szReplacer->Add(btnReplacer, 0, wxLEFT, 1);
    szMiddle->Add(szReplacer, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szTile->Add(szMiddle, 0, wxEXPAND, 0);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szTile->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szTile);
    szTile->Fit(this);
    Layout();
    // end wxGlade
}

