// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdDeletePicture.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdDeletePicture::DialogEvtCmdDeletePicture(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdDeletePicture::DialogEvtCmdDeletePicture
    szPicture_staticbox = new wxStaticBox(this, wxID_ANY, _("Picture number"));
    spinPicture = new wxSpinCtrl(this, wxID_ANY, wxT("10"), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdDeletePicture::set_properties()
{
    // begin wxGlade: DialogEvtCmdDeletePicture::set_properties
    SetTitle(_("Delete picture"));
    spinPicture->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdDeletePicture::do_layout()
{
    // begin wxGlade: DialogEvtCmdDeletePicture::do_layout
    wxBoxSizer* szDeletePicture = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szPicture_staticbox->Lower();
    wxStaticBoxSizer* szPicture = new wxStaticBoxSizer(szPicture_staticbox, wxHORIZONTAL);
    szPicture->Add(spinPicture, 1, wxALIGN_CENTER_VERTICAL, 0);
    szDeletePicture->Add(szPicture, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szDeletePicture->Add(szBottom, 0, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szDeletePicture);
    szDeletePicture->Fit(this);
    Layout();
    // end wxGlade
}

