// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdBlankScreen.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdBlankScreen::DialogEvtCmdBlankScreen(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdBlankScreen::DialogEvtCmdBlankScreen
    szMethod_staticbox = new wxStaticBox(this, wxID_ANY, _("Method"));
    const wxString chMethod_choices[] = {
        _("<set by wxGlade>"),
    };
    chMethod = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chMethod_choices);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_HELP, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdBlankScreen::set_properties()
{
    // begin wxGlade: DialogEvtCmdBlankScreen::set_properties
    SetTitle(_("Blank screen"));
    chMethod->SetMinSize(wxSize(50, -1));
    chMethod->SetSelection(0);
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdBlankScreen::do_layout()
{
    // begin wxGlade: DialogEvtCmdBlankScreen::do_layout
    wxBoxSizer* szBlankScreen = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szMethod_staticbox->Lower();
    wxStaticBoxSizer* szMethod = new wxStaticBoxSizer(szMethod_staticbox, wxHORIZONTAL);
    szMethod->Add(chMethod, 1, wxALIGN_CENTER_VERTICAL, 0);
    szBlankScreen->Add(szMethod, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALL, 1);
    szBlankScreen->Add(szBottom, 0, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szBlankScreen);
    szBlankScreen->Fit(this);
    Layout();
    // end wxGlade
}

