// -*- C++ -*-
//
// generated by wxGlade not found
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "DialogEvtCmdItem.h"

// begin wxGlade: ::extracode
// end wxGlade


DialogEvtCmdItem::DialogEvtCmdItem(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
    // begin wxGlade: DialogEvtCmdItem::DialogEvtCmdItem
    szOperand_staticbox = new wxStaticBox(this, wxID_ANY, _("Operand"));
    szObject_staticbox = new wxStaticBox(this, wxID_ANY, _("Object"));
    const wxString rbOperation_choices[] = {
        _("Add item"),
        _("Delete item"),
    };
    rbOperation = new wxRadioBox(this, wxID_ANY, _("Operation"), wxDefaultPosition, wxDefaultSize, 2, rbOperation_choices, 1, wxRA_SPECIFY_ROWS);
    rbtnObjectFixed = new wxRadioButton(this, wxID_ANY, _("Fixed"));
    const wxString chObjectFixed_choices[] = {
        _("<set by wxGlade>"),
    };
    chObjectFixed = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 1, chObjectFixed_choices);
    rbtnObjectVariable = new wxRadioButton(this, wxID_ANY, _("Variable"));
    tcObjectVariable = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnObjectVariable = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    rbtnOperandConstant = new wxRadioButton(this, wxID_ANY, _("Constant"));
    spinOperandConstant = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    rbtnOperandVariable = new wxRadioButton(this, wxID_ANY, _("Variable"));
    tcOperandVariable = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnOperandVariable = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    btnOK = new wxButton(this, wxID_OK, wxEmptyString);
    btnCancel = new wxButton(this, wxID_CANCEL, wxEmptyString);
    btnHelp = new wxButton(this, wxID_ANY, _("&Help"));

    set_properties();
    do_layout();
    // end wxGlade
}


void DialogEvtCmdItem::set_properties()
{
    // begin wxGlade: DialogEvtCmdItem::set_properties
    SetTitle(_("Change item"));
    rbOperation->SetSelection(0);
    chObjectFixed->SetMinSize(wxSize(50, -1));
    chObjectFixed->SetSelection(0);
    tcObjectVariable->SetMinSize(wxSize(50, -1));
    btnObjectVariable->SetMinSize(wxSize(-1, -1));
    spinOperandConstant->SetMinSize(wxSize(50, -1));
    tcOperandVariable->SetMinSize(wxSize(50, -1));
    btnOK->SetDefault();
    // end wxGlade
}


void DialogEvtCmdItem::do_layout()
{
    // begin wxGlade: DialogEvtCmdItem::do_layout
    wxBoxSizer* szItem = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* szBottom = new wxBoxSizer(wxHORIZONTAL);
    szOperand_staticbox->Lower();
    wxStaticBoxSizer* szOperand = new wxStaticBoxSizer(szOperand_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* gszOperand = new wxFlexGridSizer(2, 2, 2, 2);
    wxBoxSizer* szOperandVariable = new wxBoxSizer(wxHORIZONTAL);
    szObject_staticbox->Lower();
    wxStaticBoxSizer* szObject = new wxStaticBoxSizer(szObject_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* gszObject = new wxFlexGridSizer(2, 2, 2, 2);
    wxBoxSizer* szObjectVariable = new wxBoxSizer(wxHORIZONTAL);
    szItem->Add(rbOperation, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    gszObject->Add(rbtnObjectFixed, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    gszObject->Add(chObjectFixed, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    gszObject->Add(rbtnObjectVariable, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    szObjectVariable->Add(tcObjectVariable, 1, wxALIGN_CENTER_VERTICAL, 0);
    szObjectVariable->Add(btnObjectVariable, 0, wxALIGN_CENTER_VERTICAL, 0);
    gszObject->Add(szObjectVariable, 1, wxEXPAND, 0);
    gszObject->AddGrowableCol(1);
    szObject->Add(gszObject, 1, wxEXPAND, 0);
    szItem->Add(szObject, 0, wxEXPAND|wxLEFT|wxRIGHT, 1);
    gszOperand->Add(rbtnOperandConstant, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    gszOperand->Add(spinOperandConstant, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    gszOperand->Add(rbtnOperandVariable, 0, wxALIGN_CENTER_VERTICAL|wxEXPAND, 0);
    szOperandVariable->Add(tcOperandVariable, 1, wxALIGN_CENTER_VERTICAL, 0);
    szOperandVariable->Add(btnOperandVariable, 0, wxALIGN_CENTER_VERTICAL, 0);
    gszOperand->Add(szOperandVariable, 1, wxEXPAND, 0);
    gszOperand->AddGrowableCol(1);
    szOperand->Add(gszOperand, 1, wxEXPAND, 0);
    szItem->Add(szOperand, 0, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 1);
    szBottom->Add(btnOK, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnCancel, 0, wxALIGN_BOTTOM|wxALL, 1);
    szBottom->Add(btnHelp, 0, wxALIGN_BOTTOM|wxALL, 1);
    szItem->Add(szBottom, 1, wxALIGN_RIGHT|wxBOTTOM|wxRIGHT, 3);
    SetSizer(szItem);
    szItem->Fit(this);
    Layout();
    // end wxGlade
}

